{% set name = "ddsketch" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddsketch-{{ version }}.tar.gz
  sha256: 464469f53380aa878eb1dd4dc644086341e0d2a54b19dfca7d7a4645c8353ac6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - protobuf >=3.0.0
    - python >=3.6
    - six

test:
  imports:
    - ddsketch

about:
  home: http://github.com/datadog/sketches-py
  summary: Distributed quantile sketches
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aymondebroglie
